#!/usr/bin/env python3
"""
convert_ltb_report_to_md.py

Purpose:
    Convert Landlord and Tenant Board / Ontario Rental Housing Tribunal annual report PDFs
    into clean Markdown for archival and analysis.

Generated by:
    ChatGPT, GPT-5.5 Thinking
    Date: 2026-05-21

Important note:
    The original ChatGPT conversions in the project were produced using a vision-assisted,
    interactive workflow: parsed PDF text + rendered page inspection + structural cleanup.
    This script is a reproducible approximation of that workflow, not the exact internal
    ChatGPT process.

Recommended use:
    - Use for first-pass conversion.
    - Manually inspect tables, charts, page boundaries, and section cutoffs afterward.
    - Mark uncertain text as [unclear] rather than guessing.

Dependencies:
    pip install pymupdf pdfplumber
"""

from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path
from typing import Iterable, Optional

import fitz  # PyMuPDF
import pdfplumber


HEADER_FOOTER_PATTERNS = [
    r"^tribunalsontario\.ca/.*$",
    r"^SJTO\s*\|\s*.*Annual Report.*$",
    r"^Tribunals Ontario.*Annual Report.*$",
    r"^Return to Table of Contents$",
    r"^Return to Top$",
    r"^\d+\s+of\s+\d+.*$",
    r"^\d{4}-\d{2}-\d{2},?\s*\d{1,2}:\d{2}.*$",
    r"^https://tribunalsontario\.ca/.*$",
]


def clean_line(line: str) -> str:
    """Clean obvious PDF extraction artifacts without rewriting source language."""
    line = line.replace("\u00ad", "")       # soft hyphen
    line = line.replace("\ufffe", "")       # occasional OCR/control artifact
    line = line.replace("￾", "")           # common extraction artifact
    line = re.sub(r"[ \t]+", " ", line)
    return line.strip()


def is_header_footer(line: str) -> bool:
    """Return True if line looks like a repeated web/PDF header or footer."""
    stripped = line.strip()
    if not stripped:
        return False

    for pattern in HEADER_FOOTER_PATTERNS:
        if re.match(pattern, stripped, flags=re.IGNORECASE):
            return True

    return False


def markdown_table(rows: list[list[Optional[str]]]) -> str:
    """Convert a table extracted by pdfplumber into a Markdown table."""
    if not rows:
        return ""

    cleaned_rows: list[list[str]] = []
    max_cols = max(len(row) for row in rows)

    for row in rows:
        cleaned = []
        for cell in row:
            value = clean_line(cell or "")
            value = value.replace("\n", " ")
            value = value.replace("|", "\\|")
            cleaned.append(value if value else "[not reported]")

        while len(cleaned) < max_cols:
            cleaned.append("[not reported]")

        cleaned_rows.append(cleaned)

    header = cleaned_rows[0]
    body = cleaned_rows[1:]

    md = []
    md.append("| " + " | ".join(header) + " |")
    md.append("| " + " | ".join(["---"] * len(header)) + " |")

    for row in body:
        md.append("| " + " | ".join(row) + " |")

    return "\n".join(md)


def extract_page_text_with_pymupdf(pdf_path: Path, page_index: int) -> str:
    """Extract text from one page using PyMuPDF."""
    with fitz.open(pdf_path) as doc:
        page = doc[page_index]
        return page.get_text("text") or ""


def extract_page_tables_with_pdfplumber(pdf_path: Path, page_index: int) -> list[str]:
    """Extract tables from one page using pdfplumber and convert them to Markdown."""
    table_markdown: list[str] = []

    with pdfplumber.open(pdf_path) as pdf:
        page = pdf.pages[page_index]
        tables = page.extract_tables()

        for table in tables:
            md = markdown_table(table)
            if md.strip:
                table_markdown.append(md)

    return table_markdown


def normalize_heading(line: str) -> str:
    """
    Convert likely report headings to Markdown headings.

    This is intentionally conservative. It avoids rewriting ordinary prose.
    """
    line = clean_line(line)

    if not line:
        return ""

    upperish = line.upper()

    major_titles = {
        "LANDLORD AND TENANT BOARD",
        "ONTARIO RENTAL HOUSING TRIBUNAL",
        "CHAIR'S MESSAGE",
        "CHAIR’S MESSAGE",
        "YEAR IN REVIEW",
        "THE ROLE OF THE BOARD",
        "THE ADJUDICATION PROCESS",
        "THE MEDIATION PROCESS",
        "STATISTICAL INFORMATION",
        "DECISION SUMMARIES",
        "BUDGET AND REVENUES",
        "SERVICE STANDARDS",
        "OPERATIONAL HIGHLIGHTS",
        "STATISTICS",
    }

    if upperish in major_titles:
        return f"## {line}"

    if re.match(r"^Table\s+\d+[:.]\s+", line, flags=re.IGNORECASE):
        return f"### {line}"

    if re.match(r"^[A-Z][A-Za-z0-9 /&()–—'-]+:$", line):
        return f"### {line.rstrip(':')}"

    return line


def clean_text_block(text: str) -> str:
    """Clean extracted text and apply conservative heading formatting."""
    lines = text.splitlines()
    cleaned: list[str] = []

    for raw in lines:
        line = clean_line(raw)

        if not line:
            cleaned.append("")
            continue

        if is_header_footer(line):
            continue

        cleaned.append(normalize_heading(line))

    # Collapse excessive blank lines.
    joined = "\n".join(cleaned)
    joined = re.sub(r"\n{3,}", "\n\n", joined)

    return joined.strip()


def find_title_position(text: str, title: str) -> Optional[int]:
    """Find title position in text, case-insensitive."""
    match = re.search(re.escape(title), text, flags=re.IGNORECASE)
    return match.start() if match else None


def slice_text_by_titles(
    text: str,
    start_title: Optional[str] = None,
    stop_title: Optional[str] = None,
    omit_from_title: Optional[str] = None,
) -> str:
    """
    Keep text from start_title onward, stop before stop_title, and optionally
    omit everything from omit_from_title onward.
    """
    working = text

    if start_title:
        start = find_title_position(working, start_title)
        if start is not None:
            working = working[start:]

    stop_positions = []

    if stop_title:
        stop = find_title_position(working, stop_title)
        if stop is not None:
            stop_positions.append(stop)

    if omit_from_title:
        omit = find_title_position(working, omit_from_title)
        if omit is not None:
            stop_positions.append(omit)

    if stop_positions:
        working = working[: min(stop_positions)]

    return working.strip()


def extract_pdf_to_markdown(
    pdf_path: Path,
    output_path: Path,
    report_title: str,
    start_page: Optional[int] = None,
    end_page: Optional[int] = None,
    start_title: Optional[str] = None,
    stop_title: Optional[str] = None,
    omit_from_title: Optional[str] = None,
    include_tables: bool = True,
) -> None:
    """
    Convert selected PDF pages or selected titled section to Markdown.

    Page numbering:
        start_page and end_page are 1-based and inclusive.
    """
    doc = fitz.open(pdf_path)
    total_pages = len(doc)
    doc.close()

    first_index = (start_page - 1) if start_page else 0
    last_index = (end_page - 1) if end_page else total_pages - 1

    if first_index < 0 or last_index >= total_pages or first_index > last_index:
        raise ValueError(
            f"Invalid page range. PDF has {total_pages} pages; "
            f"requested {start_page}-{end_page}."
        )

    page_chunks: list[str] = []

    for page_index in range(first_index, last_index + 1):
        text = extract_page_text_with_pymupdf(pdf_path, page_index)
        text_md = clean_text_block(text)

        chunk_parts = []

        if text_md:
            chunk_parts.append(text_md)

        if include_tables:
            tables = extract_page_tables_with_pdfplumber(pdf_path, page_index)
            if tables:
                chunk_parts.append("\n\n".join(tables))

        page_chunk = "\n\n".join(chunk_parts).strip()

        if page_chunk:
            page_chunks.append(page_chunk)

    body = "\n\n".join(page_chunks)
    body = slice_text_by_titles(
        body,
        start_title=start_title,
        stop_title=stop_title,
        omit_from_title=omit_from_title,
    )

    header = f"""# {report_title}
- Source file: {pdf_path.name}
- Extraction method: PDF text extraction + table parsing + structural cleanup
- Conversion date: {date.today().isoformat()}
"""

    output = header.strip() + "\n\n" + body.strip() + "\n"
    output_path.write_text(output, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert LTB/ORHT annual report PDFs to cleaned Markdown."
    )

    parser.add_argument("pdf", type=Path, help="Input PDF path")
    parser.add_argument("--out", type=Path, help="Output Markdown path")
    parser.add_argument("--title", required=True, help="Report title for Markdown H1")

    parser.add_argument("--start-page", type=int, help="1-based inclusive start page")
    parser.add_argument("--end-page", type=int, help="1-based inclusive end page")

    parser.add_argument(
        "--start-title",
        default=None,
        help='Keep text starting at this title, e.g. "Landlord and Tenant Board"',
    )
    parser.add_argument(
        "--stop-title",
        default=None,
        help='Stop before this title, e.g. "Licence Appeal Tribunal"',
    )
    parser.add_argument(
        "--omit-from-title",
        default=None,
        help='Omit this section and everything after, e.g. "Biographies"',
    )
    parser.add_argument(
        "--no-tables",
        action="store_true",
        help="Disable pdfplumber table extraction",
    )

    args = parser.parse_args()

    pdf_path = args.pdf
    output_path = args.out or pdf_path.with_suffix(".md")

    extract_pdf_to_markdown(
        pdf_path=pdf_path,
        output_path=output_path,
        report_title=args.title,
        start_page=args.start_page,
        end_page=args.end_page,
        start_title=args.start_title,
        stop_title=args.stop_title,
        omit_from_title=args.omit_from_title,
        include_tables=not args.no_tables,
    )

    print(f"Wrote Markdown to: {output_path}")


if __name__ == "__main__":
    main()
